version: '3.8'

services:
  crontab-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crontab-go
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - /var/log:/var/log:ro  # 只读挂载日志目录，用于日志清理任务
    environment:
      - TZ=Asia/Shanghai
      - DB_PATH=/app/data/crontab.db
      - JWT_SECRET=your-jwt-secret-key-change-this-in-production
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/system/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - crontab-network

  # 可选：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: crontab-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL 证书目录
    depends_on:
      - crontab-go
    restart: unless-stopped
    networks:
      - crontab-network

networks:
  crontab-network:
    driver: bridge

volumes:
  crontab-data:
    driver: local