name: Simple Test

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  simple-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Print Go version
      run: go version

    - name: Check Go modules
      run: go mod tidy

    - name: Build application
      run: go build -o crontab_go ./cmd

    - name: Test help command
      run: ./crontab_go --help

    - name: Print success message
      run: echo "✅ Build and basic test completed successfully!"